### PR TITLE
Added support for systemd based distributions

### PR DESCRIPTION
**Pull request by cameris**
Systemd based distributions link /etc/localtime to a tzfile. The path of the tzfile contains the timezone identifier. See manpages localtime(5) and timedatectl(1).

### CODE REVIEW

**Comment by cameris** [comment]
Apperantley you already mentioned this in Unix Step 2 of
http://regebro.wordpress.com/2008/05/10/python-and-time-zones-part-2-the-beast-returns/

But using the current tzlocal only results in "local" zone for the systemd distributions that I tested (Archlinux and SailfishOS).

**Comment by BenjamenMeyer** [comment]
@cameris is the distro setup correctly?

I ask because I have run into that myself where I though the distro was setup one way and it turned out it wasn't.

Note: if using a system that dual boots with Windows, then this complicates things as Windows has to have the hardware time set to localtime which then messes up how the TZs are set in Linux.

Note: looking at the path is not a reliable way of determining the timezone.

**Comment by cameris** [comment]
Could you ellaborate what you mean by setup correctly?
ArchLinux was setup after their wiki. It dualboots with Windows 7, but set up Windows to use UTC and never had problems with it:
https://wiki.archlinux.org/index.php/Time#UTC_in_Windows

A stock SailfishOS runs on my mobile, so I never messed with it.

Since manpage localtime(5), which belongs to systemd, states about /etc/localtime:
'It should be an absolute or relative symbolic link pointing to /usr/share/zoneinfo/, followed by a timezone identifier such as "Europe/Berlin" or "Etc/UTC".'
Therefore I thought it should be pretty reliable, at least for systemd distros.

**Comment by BenjamenMeyer** [comment]
@cameris - many distros will simply copy the timezone file over the file in /etc/localtime instead of symlinking to it, thus it is not reliable to look at the path in any form of the file; nor is that meant as a means of decoding the timezone. I doubt that systemd has changed that at all as it really has nothing to do with the setup of the timezone file. The only way to reliably use the timezone file is to actually use it; or comparing it to the files in the timezone listing.

Further, timezones are configured on a per-user basis via (i) setting of the hardware clock via /etc/localtime, and (ii) user configuration (environment variables, etc).

If you are keeping Windows in UTC then that may help you; but I'm not sure - depends on what Windows does underneath, but it should work in your favor since AFAIK Windows doesn't do offsetting so much as it just uses the hardware clock to determine local time. However, if you change your user in Windows to a different timezone you'll likely mess it up.

Just make sure the following reports correctly:
```bash
$ date
Tue Jan 13 14:07:56 UTC 2015
$ date -u
Tue Jan 13 14:07:57 UTC 2015
```
They report the same for me as that was a system that I only have setup for UTC, even for the user. The first should be your timezone configuration and the second UTC.

**Comment by cameris** [comment]
@BenjamenMeyer - from what if figured it is exactly what systemd does:
https://github.com/systemd/systemd/blob/07bde8c0ff9b12e0236374b9f7490909ddf8d213/src/timedate/timedated.c#L74-106
So it should be reliable, but as said, only for systemd distros.

Since tzlocal only checks files (/etc/timezone, /etc/sysconfig/clock, /etc/conf.d/clock) which are not present on (pure?) systemd distros, there is no way to determine the zone name otherwise.

Note: Haven't tried the date cmd yet, but will do asap.

**Comment by regebro** [comment]
I know there's not many tests, but is there a possibility to add one for this case?

**Comment by cameris** [comment]
Added test case, hope this is what you had in mind.

**Comment by tbabej** [comment]
Can we get this merged? Timezones without name are pain, since pytz does not recognize them #18.

**Comment by tbabej** [comment]
I can confirm that cameris's patch works fine with systemd-216-17.

**Comment by tbabej** [comment]
Any updates on this?

**Comment by deronnax** [comment]
Hello. I have the the problem on Fedora 17+. Now Fedora ships with systemd, and I can' t have the timezone name. 
In django-cms we are writing an helper function for automatically determining user settings and thus configuring django, including locale timezone, and we are blocked on this.
I just tried camaris patch on my Fedora and I confirm it works.

**Comment by tbabej** [comment]
As per http://en.wikipedia.org/wiki/Systemd#Adoption_and_reception , this is also problem on recent versions of: ArchLinux, CoreOS, Fedora, Mageia, openSUSE, Oracle Linux, RHEL, SLES  now and will be also problem on Debian and Ubuntu in the near future.

**Comment by regebro** [comment]
Yeah, sorry, I finally got time to check this out on a Fedora system.

**Comment by tbabej** [comment]
Great, thanks! Will you release a new package version with this fix?

**Comment by regebro** [comment]
Done!

**Pull request merged**
