### PR TITLE
Assert that system's offset equals to the timezone offset found

### PR DESCRIPTION
**Pull request by victor-torres**
If they don't match, we probably have a misconfiguration, for example, an incorrect timezone set in /etc/timezone file in systemd distributions.

We're raising an AssertionError, but it could be easily replaced with a soft warning if needed.

### CODE REVIEW

**Comment by regebro** [comment]
That seems a reasonable check.

Any reason you make the call with ctypes instead of using the functions in stdlib?

Also, libc.timezone (like time.timezone in stdlib) contains the non-DST offset, so this fails as soon as you have daylight savings time.

**Comment by victor-torres** [comment]
I need to check the tests. Also, now that it's using the built-in library, I'll move the code to a util.py file and also assert the offsets in Windows.

**Comment by victor-torres** [comment]
Could you check again, pleae? @regebro

**Comment by regebro** [comment]
Merged

**Pull request closed without merging**
